apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/samirelhassan/personal-projects/fiap/fiap-phase-02/tech-challenge/tech-challenge-02/deploy/local/db/volume"
