apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    name: api-config
data:
  POSTGRES_URL: postgresql://docker:ps123@svc-db:5432/tech-challenge
  MERCADO_PAGO_GENERATE_PAYMENT: "off"
  MERCADO_PAGO_WEBHOOK_URL: https://webhook.site/ad40ef19-51ed-4b1c-bd03-98a92f99550a
  MERCADO_PAGO_API_HOST: https://api.mercadopago.com
  MERCADO_PAGO_BEARER_TOKEN: TEST-509899401579038-012212-e96aae51275244a79f540cc3f95e9d59-359694122
  MERCADO_PAGO_USER_ID: "359694122"
  MERCADO_PAGO_EXTERNAL_POS_ID: SUC001